### ISSUE TITLE
Could you add this paper to the list.

### ISSUE THREAD

**Issue by revanurambareesh** [lzhbrian/Cool-Fashion-Papers#10]
Paper:- Semi-Supervised Visual Representation Learning for Fashion Compatibility

Venue:- ACM RecSys'21
PDF Link:- https://arxiv.org/pdf/2109.08052.pdf
Additional Resources:- https://dl.acm.org/doi/10.1145/3460231.3474233

Thanks!

**Comment by lzhbrian** [comment]
Sure, added in https://github.com/lzhbrian/Cool-Fashion-Papers/commit/0f460a49c1afd77543a9ee4b5b25ba608ff6c6c9. Thanks!
