### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by andrewjong** [lzhbrian/Cool-Fashion-Papers#4]
Thanks for compiling this list! I've made an unofficial reproduction for SwapNet, could you let me know the preferred way to contribute? Shall I open a pull request?

My implementation is here: https://github.com/andrewjong/swapnet. Thanks!

**Comment by lzhbrian** [comment]
Hi, you are welcomed to contribute!
Please just make a PR directly to README.md if you would like.

**Comment by andrewjong** [comment]
Cool, I opened a PR. Can you review it, please?
